export const PATIENT_SIGNUP = "PATIENT_SIGNUP";
export const PATIENT_SIGNUP_SUCCED = "PATIENT_SIGNUP_SUCCED";
export const PATIENT_SIGNUP_FAILED = "PATIENT_SIGNUP_FAILED";

export const PATIENT_SIGNIN = "PATIENT_SIGNIN";
export const PATIENT_SIGNIN_SUCCED = "PATIENT_SIGNIN_SUCCED";
export const PATIENT_SIGNIN_FAILED = "PATIENT_SIGNIN_FAILED";

export const GET_ALL_DOCTORS = "GET_ALL_DOCTORS";
export const GET_ALL_DOCTORS_SUCCED = "GET_ALL_DOCTORS_SUCCED";
export const GET_ALL_DOCTORS_FAILED = "GET_ALL_DOCTORS_FAILED";
